export const colors = {
  primary: "#005f42",
  primaryContainer: "#0d7a57",
  onPrimary: "#ffffff",
  onPrimaryContainer: "#a7ffd5",
  primaryFixed: "#98f5ca",
  primaryFixedDim: "#7cd8af",
  onPrimaryFixed: "#002114",
  onPrimaryFixedVariant: "#005138",
  inversePrimary: "#7cd8af",
  surfaceTint: "#006c4c",
  secondary: "#545f73",
  secondaryContainer: "#d5e0f8",
  onSecondary: "#ffffff",
  onSecondaryContainer: "#586377",
  secondaryFixed: "#d8e3fb",
  onSecondaryFixed: "#111c2d",
  onSecondaryFixedVariant: "#3c475a",
  tertiary: "#006029",
  tertiaryContainer: "#007c36",
  onTertiary: "#ffffff",
  onTertiaryContainer: "#b2ffba",
  tertiaryFixed: "#66ff8e",
  onTertiaryFixed: "#002109",
  background: "#f8f9ff",
  surface: "#f8f9ff",
  surfaceBright: "#f8f9ff",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#eff4ff",
  surfaceContainer: "#e5eeff",
  surfaceContainerHigh: "#dce9ff",
  surfaceContainerHighest: "#d3e4fe",
  surfaceVariant: "#d3e4fe",
  surfaceDim: "#cbdbf5",
  onSurface: "#0b1c30",
  onBackground: "#0b1c30",
  onSurfaceVariant: "#3e4943",
  inverseSurface: "#213145",
  inverseOnSurface: "#eaf1ff",
  outline: "#6e7a72",
  outlineVariant: "#bec9c1",
  error: "#ba1a1a",
  onError: "#ffffff",
  errorContainer: "#ffdad6",
  onErrorContainer: "#93000a",
  whatsapp: "#25D366",
  whatsappOn: "#064E3B",
  trustMint: "#ECFDF5",
  trustMintBorder: "#A7F3D0",
} as const;

export const space = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  margin: 16,
  gutter: 12,
} as const;

export const radius = {
  sm: 4,
  lg: 8,
  xl: 12,
  full: 9999,
} as const;

export const fonts = {
  headline: "PlusJakartaSans_700Bold",
  headlineSemi: "PlusJakartaSans_600SemiBold",
  headlineExtra: "PlusJakartaSans_800ExtraBold",
  body: "NotoSans_400Regular",
  bodyMedium: "NotoSans_500Medium",
  bodySemi: "NotoSans_600SemiBold",
  bodyBold: "NotoSans_700Bold",
} as const;

export const type = {
  headlineXlMobile: { fontSize: 26, lineHeight: 34, fontWeight: "700" as const, fontFamily: fonts.headline },
  headlineLg: { fontSize: 24, lineHeight: 32, fontWeight: "700" as const, fontFamily: fonts.headline },
  headlineLgMobile: { fontSize: 20, lineHeight: 28, fontWeight: "700" as const, fontFamily: fonts.headline },
  headlineMd: { fontSize: 18, lineHeight: 26, fontWeight: "600" as const, fontFamily: fonts.headlineSemi },
  bodyLg: { fontSize: 16, lineHeight: 24, fontWeight: "500" as const, fontFamily: fonts.bodyMedium },
  bodyMd: { fontSize: 14, lineHeight: 22, fontWeight: "400" as const, fontFamily: fonts.body },
  bodySm: { fontSize: 13, lineHeight: 18, fontWeight: "400" as const, fontFamily: fonts.body },
  labelLg: { fontSize: 14, lineHeight: 20, fontWeight: "600" as const, fontFamily: fonts.bodySemi },
  labelMd: { fontSize: 12, lineHeight: 16, fontWeight: "600" as const, fontFamily: fonts.bodySemi },
  labelSm: { fontSize: 11, lineHeight: 14, fontWeight: "600" as const, fontFamily: fonts.bodySemi },
} as const;
