"""Twin-cities hospitality catalogue. Idempotent: upsert on slug / (parent, slug).

Business types (D1): restaurant, hotel, grocery only — stored on businesses in Phase 3, not here.
"""

from __future__ import annotations

# (slug, name_en, name_ur, aliases)
PROFESSIONS: list[tuple[str, str, str, list[str]]] = [
    ("cook", "Cook / Chef", "باورچی / شیف", ["bawarchi", "chef", "karahi cook", "tandoor", "head cook", "head chef"]),
    ("waiter", "Waiter / Server", "ویٹر", ["waiter", "captain", "steward", "front hall", "server", "waiter wala"]),
    ("rider", "Delivery rider", "ڈیلیوری رائیڈر", ["rider", "rider wala", "delivery boy", "bike rider"]),
    ("cashier", "Cashier", "کیشیئر", ["cashier", "billing", "counter", "pos"]),
    ("cleaner", "Cleaner / Dishwasher", "صفائی / برتن دھونا", ["safai", "dishwasher", "kitchen cleaner", "sweeper", "housekeeping helper"]),
    ("kitchen-helper", "Kitchen helper", "کچن ہیلپر", ["helper", "kitchen boy", "assistant cook", "mazdoor kitchen"]),
    ("grocery-helper", "Grocery / stock helper", "گروسری ہیلپر", ["stock", "packer", "shelf", "store helper", "retail helper"]),
    ("housekeeping", "Hotel housekeeping", "ہاؤس کیپنگ", ["housekeeper", "room boy", "room attendant", "bellboy"]),
]

# (slug, profession_slug | None, name_en, name_ur, aliases)
SKILLS: list[tuple[str, str | None, str, str, list[str]]] = [
    # Cook
    ("shinwari-karahi", "cook", "Shinwari karahi", "شنواری کڑاہی", ["karahi", "shinwari"]),
    ("mutton-handi", "cook", "Mutton handi", "مٹن ہانڈی", ["handi"]),
    ("chicken-karahi", "cook", "Chicken karahi", "چکن کڑاہی", ["karahi chicken"]),
    ("koyla-bbq", "cook", "Koyla BBQ", "کوئلہ باربی کیو", ["bbq", "seekh", "tikka"]),
    ("tandoor", "cook", "Tandoor / naan", "تندور / نان", ["tandoori", "naan", "roti"]),
    ("biryani", "cook", "Biryani", "بریانی", ["pulao"]),
    ("chinese-pakistani", "cook", "Pakistani Chinese", "پاکستانی چائنیز", ["chowmein", "manchurian"]),
    ("fast-food-cook", "cook", "Fast food cook", "فاسٹ فوڈ", ["burger", "fries", "broast"]),
    ("dum-pukht", "cook", "Dum pukht", "دم پخت", ["slow cook"]),
    ("knife-prep", "cook", "Knife & prep", "کاٹنا اور تیاری", ["prep", "cutting"]),
    ("masala", "cook", "Masala / gravy", "مصالحہ / گریوی", ["gravy", "salan"]),
    ("bakery-oven", "cook", "Bakery / oven", "بیکری", ["cake", "oven"]),
    ("breakfast-cook", "cook", "Breakfast cook", "ناشتہ", ["paratha", "omelette"]),
    ("dessert", "cook", "Dessert / sweet", "میٹھا", ["kheer", "custard"]),
    ("hygiene-cook", "cook", "Kitchen hygiene", "کچن صفائی", ["hygiene", "food safety"]),
    ("team-lead-kitchen", "cook", "Kitchen team lead", "کچن سربراہ", ["head chef", "leadership"]),
    ("inventory-kitchen", "cook", "Kitchen inventory", "انوینٹری", ["store", "stock kitchen"]),
    ("live-bbq", "cook", "Live BBQ counter", "لائیو باربی کیو", ["live station"]),
    # Waiter
    ("table-service", "waiter", "Table service", "ٹیبل سروس", ["serving"]),
    ("order-taking", "waiter", "Order taking", "آرڈر لینا", ["order"]),
    ("billing-waiter", "waiter", "Billing / bill present", "بل", ["bill"]),
    ("banquet", "waiter", "Banquet / events", "بنکٹ", ["function", "shadi"]),
    ("room-service", "waiter", "Room service", "روم سروس", ["in room"]),
    ("captain", "waiter", "Captain / shift lead", "کیپٹن", ["head waiter"]),
    ("english-menu", "waiter", "English menu reading", "انگریزی مینو", ["english"]),
    ("urdu-guest", "waiter", "Urdu guest handling", "اردو مہمان", ["mehman"]),
    ("pos-waiter", "waiter", "POS / handheld", "پی او ایس", ["pos"]),
    ("tray-service", "waiter", "Tray / platter", "ٹرے", ["platter"]),
    # Rider
    ("bike-own", "rider", "Own motorcycle", "اپنی موٹر سائیکل", ["bike"]),
    ("foodpanda", "rider", "Foodpanda / apps", "فوڈپانڈا", ["bykea", "careem"]),
    ("city-nav-isb", "rider", "Islamabad navigation", "اسلام آباد راستے", ["sectors"]),
    ("city-nav-rwp", "rider", "Rawalpindi navigation", "راولپنڈی راستے", ["saddar"]),
    ("cash-cod", "rider", "Cash on delivery", "کیش آن ڈیلیوری", ["cod"]),
    ("food-bag", "rider", "Hot bag handling", "گرم بیگ", ["thermal"]),
    ("cnic-license", "rider", "Valid license", "لائسنس", ["driving license"]),
    # Cashier
    ("pos-cashier", "cashier", "POS / till", "کیش کاؤنٹر", ["till"]),
    ("barcode", "cashier", "Barcode scanning", "بارکوڈ", ["scanner"]),
    ("returns", "cashier", "Returns / voids", "واپسی", ["refund"]),
    ("shift-close", "cashier", "Shift closing", "شفٹ کلوز", ["z report"]),
    ("card-machine", "cashier", "Card machine", "کارڈ مشین", ["jazzcash", "easypaisa"]),
    ("customer-queue", "cashier", "Queue handling", "قطار", ["counter rush"]),
    # Cleaner
    ("dish-wash", "cleaner", "Dishwashing", "برتن دھونا", ["pots"]),
    ("floor-mop", "cleaner", "Floor mopping", "فرش", ["mop", "jharu"]),
    ("washroom", "cleaner", "Washroom cleaning", "واش روم", ["toilet"]),
    ("kitchen-deep", "cleaner", "Kitchen deep clean", "کچن گہری صفائی", ["hood"]),
    ("garbage", "cleaner", "Garbage / waste", "کوڑا", ["waste"]),
    ("laundry", "cleaner", "Laundry assist", "لانڈری", ["sheets"]),
    # Kitchen helper
    ("veg-cut", "kitchen-helper", "Vegetable cutting", "سبزی کاٹنا", ["prep helper"]),
    ("tandoor-help", "kitchen-helper", "Tandoor helper", "تندور ہیلپر", ["roti helper"]),
    ("dishwasher-help", "kitchen-helper", "Pot wash assist", "برتن مدد", ["pots helper"]),
    ("store-fetch", "kitchen-helper", "Store fetching", "اسٹور سے لانا", ["masala fetch"]),
    ("oil-fry", "kitchen-helper", "Frying assist", "تلنا", ["karahi help"]),
    # Grocery
    ("shelf-stock", "grocery-helper", "Shelf stocking", "شیلف بھرنا", ["facing"]),
    ("expiry-check", "grocery-helper", "Expiry check", "ایکسپائری", ["fifo"]),
    ("receive-stock", "grocery-helper", "Receiving stock", "مال اتارنا", ["unload"]),
    ("weigh-counter", "grocery-helper", "Weighing counter", "تولنا", ["sabzi weigh"]),
    ("cold-store", "grocery-helper", "Cold store", "کولڈ سٹور", ["freezer"]),
    ("night-shift-retail", "grocery-helper", "Night shift", "نائٹ شفٹ", ["late"]),
    # Housekeeping
    ("room-make", "housekeeping", "Room making", "کمرہ لگانا", ["bed"]),
    ("towel", "housekeeping", "Towel / linen", "تولیہ", ["linen"]),
    ("minibar", "housekeeping", "Minibar restock", "منی بار", ["minibar"]),
    ("turndown", "housekeeping", "Turndown service", "ٹرن ڈاؤن", ["evening"]),
    ("public-area", "housekeeping", "Public area clean", "لانج صفائی", ["lobby"]),
    # Cross-cutting
    ("hygiene", None, "Personal hygiene", "ذاتی صفائی", ["clean uniform"]),
    ("punctual", None, "Punctual / shift on time", "وقت پر آنا", ["on time"]),
    ("night-shift", None, "Night / evening shift", "رات / شام شفٹ", ["dinner rush"]),
    ("ramadan-hours", None, "Ramadan / sehri hours", "رمضان", ["sehri", "iftar"]),
    ("no-smoke", None, "Non-smoker preferred", "غیر تمباکو", ["non smoker"]),
    ("cnic-valid", None, "Valid CNIC", "شناختی کارڈ", ["cnic"]),
    ("whatsapp", None, "WhatsApp communication", "واٹس ایپ", ["whatsapp"]),
    ("urdu-spoken", None, "Spoken Urdu", "بول چال اردو", ["urdu"]),
    ("punjabi-spoken", None, "Spoken Punjabi", "پنجابی", ["punjabi"]),
    ("pashto-spoken", None, "Spoken Pashto", "پشتو", ["pashto"]),
    ("teamwork", None, "Teamwork", "ٹیم ورک", ["team"]),
    ("guest-facing", None, "Guest facing", "مہمانوں سے بات", ["front"]),
    ("heavy-lift", None, "Can lift stock / pots", "وزن اٹھانا", ["physical"]),
    ("uniform", None, "Own uniform / grooming", "یونيفارم", ["grooming"]),
]

# Areas under a city: (slug, name_en, name_ur)
ISLAMABAD_AREAS = [
    ("blue-area", "Blue Area", "بلو ایریا"),
    ("f-5", "F-5", "ایف-5"),
    ("f-6", "F-6 / Jinnah Super", "ایف-6"),
    ("f-7", "F-7 Markaz", "ایف-7 مرکز"),
    ("f-8", "F-8 Markaz", "ایف-8 مرکز"),
    ("f-10-markaz", "F-10 Markaz", "ایف-10 مرکز"),
    ("f-11", "F-11 Markaz", "ایف-11"),
    ("g-6", "G-6 / Aabpara", "جی-6 / آبپارہ"),
    ("g-7", "G-7", "جی-7"),
    ("g-8", "G-8 Markaz", "جی-8"),
    ("g-9", "G-9 / Karachi Company", "جی-9 / کراچی کمپنی"),
    ("g-10", "G-10", "جی-10"),
    ("g-11", "G-11", "جی-11"),
    ("g-13", "G-13", "جی-13"),
    ("i-8", "I-8 Markaz", "آئی-8 مرکز"),
    ("i-9", "I-9", "آئی-9"),
    ("i-10", "I-10", "آئی-10"),
    ("i-11", "I-11", "آئی-11"),
    ("h-8", "H-8", "ایچ-8"),
    ("h-9", "H-9", "ایچ-9"),
    ("e-11", "E-11", "ای-11"),
    ("melody", "Melody / Centaurus", "میلوڈی / سینٹاروس"),
    ("diplomatic-enclave", "Diplomatic Enclave", "ڈپلومیٹک اینکلیو"),
    ("bahria-enclave", "Bahria Enclave", "بحریہ اینکلیو"),
    ("dha-islamabad", "DHA Islamabad", "ڈی ایچ اے اسلام آباد"),
    ("pwd", "PWD", "پی ڈبلیو ڈی"),
    ("soan-garden", "Soan Garden", "سوان گارڈن"),
    ("tarlai", "Tarlai", "ترلائی"),
    ("bani-gala", "Bani Gala", "بنی گالا"),
    ("g-15", "G-15", "جی-15"),
]

RAWALPINDI_AREAS = [
    ("saddar", "Saddar", "صدر"),
    ("committee-chowk", "Committee Chowk", "کمیٹی چوک"),
    ("raja-bazaar", "Raja Bazaar", "راجہ بازار"),
    ("commercial-market", "Commercial Market", "کمرشل مارکیٹ"),
    ("sixth-road", "Sixth Road", "سکسٹھ روڈ"),
    ("murree-road", "Murree Road", "مری روڈ"),
    ("stadium-road", "Stadium Road", "اسٹیڈیم روڈ"),
    ("satellite-town", "Satellite Town", "سیٹلائٹ ٹاؤن"),
    ("westridge", "Westridge", "ویسٹ رج"),
    ("peshawar-road", "Peshawar Road", "پشاور روڈ"),
    ("chaklala", "Chaklala", "چکلالہ"),
    ("chaklala-scheme-3", "Chaklala Scheme 3", "چکلالہ سکیم 3"),
    ("rwp-cantt", "Rawalpindi Cantt", "راولپنڈی کینٹ"),
    ("civil-lines", "Civil Lines", "سول لائنز"),
    ("bahria-town-rwp", "Bahria Town Rawalpindi", "بحریہ ٹاؤن راولپنڈی"),
    ("dha-rwp", "DHA Rawalpindi", "ڈی ایچ اے راولپنڈی"),
    ("askari-14", "Askari 14", "عسکری 14"),
    ("tench-bhatta", "Tench Bhatta", "ٹینچ بھٹہ"),
    ("waris-khan", "Waris Khan", "وارث خان"),
    ("faizabad", "Faizabad", "فیض آباد"),
    ("ijp-road", "IJP Road", "آئی جے پی روڈ"),
    ("pir-wadhai", "Pir Wadhai", "پیر ودھائی"),
    ("adiala-road", "Adiala Road", "ادیالہ روڈ"),
    ("sadiqabad-rwp", "Sadiqabad", "صادق آباد"),
    ("harley-street", "Harley Street", "ہارلی سٹریٹ"),
    ("airport-rwp", "Airport / DHA-II approach", "ایئرپورٹ"),
]
